# Generated by Django 3.2.6 on 2021-08-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi', '0002_auto_20210825_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reased',
            new_name='readed',
        ),
    ]
